---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  tasks:
    # Данный шаг вызывает роль system-prepare для прогона тестов с помощью Molecule:
    - name: "Include system-prepare role for testing"
      include_role:
        name: "system-prepare"
