---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: opensuse15.5
    image: mdd13/ansible-docker-suse:opensuse15.5
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: opensuse15.6
    image: mdd13/ansible-docker-suse:opensuse15.6
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: centos8
    image: mdd13/ansible-docker-redhat:centos8
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: centos9
    image: mdd13/ansible-docker-redhat:centos9
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: redhat8
    image: mdd13/ansible-docker-redhat:redhat8
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: redhat9
    image: mdd13/ansible-docker-redhat:redhat9
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: debian10
    image: mdd13/ansible-docker-debian:debian10
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: debian11
    image: mdd13/ansible-docker-debian:debian11
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: debian12
    image: mdd13/ansible-docker-debian:debian12
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: ubuntu20.04
    image: mdd13/ansible-docker-ubuntu:ubuntu20.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: ubuntu22.04
    image: mdd13/ansible-docker-ubuntu:ubuntu22.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

  - name: ubuntu24.04
    image: mdd13/ansible-docker-ubuntu:ubuntu24.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: host
    override_command: false
    security_opts:
      - seccomp=unconfined

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

verifier:
  name: ansible
